export const SYMBOLS = [
  'AMZN',
  'AAPL',
  'GOOG',
  'META',
  'MSFT',
  'NFLX',
  'TSLA',
  'PLTR',
  'ORCL',
  'AMD',
  'MU',
  'NVDA',
  'QCOM',
  'AVGO',
  'SOXL',
  'DASH',
  'LYFT',
  'UBER',
  'HD',
  'LOW',
  'WMT',
  'DIA',
  'QQQ',
  'SPY',
  'SPX',
  'IWM',
  'TNA',
  'AXP',
  'C',
  'MA',
  'PYPL',
  'V',
  'BABA',
  'LI',
  'NIO',
  'XPEV',
  'GLD',
  'SLV',
  'USO',
  'COIN',
  'HOOD',
  'CVS',
  'MRNA',
  'PFE',
  'BA',
  'URA',
] as const;

export interface SymbolGroup {
  id: string;
  label: string;
  symbols: string[];
}

export const SYMBOL_GROUPS: SymbolGroup[] = [
  { id: 'technology', label: 'Technology', symbols: ['AMZN', 'AAPL', 'GOOG', 'META', 'MSFT', 'NFLX', 'TSLA', 'PLTR', 'ORCL'] },
  { id: 'semiconductors', label: 'Semiconductors', symbols: ['AMD', 'MU', 'NVDA', 'QCOM', 'AVGO', 'SOXL'] },
  { id: 'software-app', label: 'Software - App', symbols: ['DASH', 'LYFT', 'UBER'] },
  { id: 'consumer', label: 'Consumer', symbols: ['HD', 'LOW', 'WMT'] },
  { id: 'index-usa', label: 'Index - USA', symbols: ['DIA', 'QQQ', 'SPY', 'SPX'] },
  { id: 'financial-exchange', label: 'Financial / Exchange', symbols: ['IWM', 'TNA'] },
  { id: 'cards', label: 'Cards', symbols: ['AXP', 'C', 'MA', 'PYPL', 'V'] },
  { id: 'china', label: 'China', symbols: ['BABA', 'LI', 'NIO', 'XPEV'] },
  { id: 'commodity', label: 'Commodity', symbols: ['GLD', 'SLV', 'USO'] },
  { id: 'financial-data', label: 'Financial / Data', symbols: ['COIN', 'HOOD'] },
  { id: 'healthcare', label: 'Healthcare', symbols: ['CVS', 'MRNA', 'PFE'] },
  { id: 'industrials', label: 'Industrials', symbols: ['BA'] },
  { id: 'nuclear-energy', label: 'Nuclear Energy', symbols: ['URA'] },
];

export const SYMBOL_NAMES: Record<string, string> = {
  AMZN: 'Amazon.com, Inc.',
  AAPL: 'Apple Inc.',
  GOOG: 'Alphabet Inc. (Class C)',
  META: 'Meta Platforms, Inc.',
  MSFT: 'Microsoft Corporation',
  NFLX: 'Netflix, Inc.',
  TSLA: 'Tesla, Inc.',
  PLTR: 'Palantir Technologies Inc.',
  ORCL: 'Oracle Corporation',
  AMD: 'Advanced Micro Devices, Inc.',
  MU: 'Micron Technology, Inc.',
  NVDA: 'NVIDIA Corporation',
  QCOM: 'QUALCOMM Incorporated',
  AVGO: 'Broadcom Inc.',
  SOXL: 'Direxion Daily Semiconductor Bull 3X Shares (ETF)',
  DASH: 'DoorDash, Inc.',
  LYFT: 'Lyft, Inc.',
  UBER: 'Uber Technologies, Inc.',
  HD: 'The Home Depot, Inc.',
  LOW: "Lowe's Companies, Inc.",
  WMT: 'Walmart Inc.',
  DIA: 'SPDR Dow Jones Industrial Average ETF Trust',
  QQQ: 'Invesco QQQ Trust',
  SPY: 'SPDR S&P 500 ETF Trust',
  SPX: 'S&P 500 Index',
  IWM: 'iShares Russell 2000 ETF',
  TNA: 'Direxion Daily Small Cap Bull 3X Shares (ETF)',
  AXP: 'American Express Company',
  C: 'Citigroup Inc.',
  MA: 'Mastercard Incorporated',
  PYPL: 'PayPal Holdings, Inc.',
  V: 'Visa Inc.',
  BABA: 'Alibaba Group Holding Limited',
  LI: 'Li Auto Inc.',
  NIO: 'NIO Inc.',
  XPEV: 'XPeng Inc.',
  GLD: 'SPDR Gold Shares (ETF)',
  SLV: 'iShares Silver Trust (ETF)',
  USO: 'United States Oil Fund, LP (ETF)',
  COIN: 'Coinbase Global, Inc.',
  HOOD: 'Robinhood Markets, Inc.',
  CVS: 'CVS Health Corporation',
  MRNA: 'Moderna, Inc.',
  PFE: 'Pfizer Inc.',
  BA: 'The Boeing Company',
  URA: 'Global X Uranium ETF',
};
